name = "who"
version = "1.0.0"
target = "javascript"

description = "🥸 Who am I?"
licences = ["Apache-2.0"]
repository = { type = "github", user = "daniellionel01", repo = "who-am-i" }
links = [{ title = "Website", href = "https://who-am-i-three-xi.vercel.app/" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
glaze_basecoat = ">= 3.1.0 and < 4.0.0"
iv = ">= 1.4.2 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"

[tools.lustre.html]
scripts = [{ src = "https://cdn.jsdelivr.net/npm/basecoat-css@0.3.11/dist/js/all.min.js" }]
meta = [{ rel="icon", href="https://fav.farm/%F0%9F%A5%B8" }]
