name = "who"
version = "1.0.0"

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
wisp = ">= 1.8.0 and < 2.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
lustre = ">= 5.3.2 and < 6.0.0"
choire = ">= 1.0.7 and < 2.0.0"
parrot = ">= 1.2.6 and < 2.0.0"
sqlight = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
